version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - my-db:/home/ventu/docker/bbdd/mysql
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  my-db:
